# References

\index{reference sources}
1. Core R Team (Ed.), \index{R Core Team} [R Reference Index](https://cran.cnr.berkeley.edu/doc/manuals/r-release/fullrefman.pdf), R Foundation for Statistical Computing, Vienna, 2018.

2. Hellmann, Doug \index{Hellmann, Doug}; [The Python 3 Standard Library by example](https://www.amazon.com/Python-Standard-Library-Example-Developers-ebook/dp/B072QZZDV7), Addison-Wesley, Boston MA, 2017.

3. Python Software Foundation \index{Python Software Foundation} (Ed.)., [Python 3.7.1 documentation](https://docs.python.org/3.7/),  Python Software Foundation, Wilmington Delaware, 2018

4. RStudio\index{RStudio} Consortium (Ed.), [RStudio Documentation](https://support.rstudio.com/hc/en-us/categories/200035113-Documentation),  Boston MA, 2018

5. Core R Team (Ed.), [R Language Reference](https://cran.r-project.org/doc/manuals/r-release/R-lang.html), R Foundation for Statistical Computing, Vienna, 2018.

6. Python Software Foundation(Ed.), [Python Package Index](https://pypi.org/), Wilmington Delaware, 2018

7. Dalgaard, Peter \index{Dalgaard, Peter}; Introductory Statistics with R, Springer-Valng, New York NY, 2002.

8. Lutz, Mark \{Lutz, Mark}; Learning Python 4^th^ Ed., O’Reilly Media, Sebastopol CA, 2009.

9. Grus, Joel \index{Grus, Joel}; Data Science from Scratch, First Principles with Python, O’Reilly Media, Sebastopol CA, 2015

10. Boschetti, Alberto; Luca Massaron; Python Data Science Essentials, Packt Publishing, Birmingham UK, 2015

11. Perktold, Josef \index{Perktold, Josef}; Skipper Seabold; Jonathan Taylor; [StatsModels](https://www.statsmodels.org/stable/index.html) Washington DC Chicago IL, 2017

12. Skipper Seabold; Perktold, Josef; "Statsmodels: Econometric and Statistical Modeling with Python", PROC. OF THE 9th PYTHON IN SCIENCE CONF. (SCIPY 2010) 

13. Veneble W. index{Veneble W.}; B. Ripley; [Modern Applied Statistics with S](https://www.amazon.com/Modern-Applied-Statistics-Computing-ebook/dp/B000S1LWTE/ref=mt_kindle?_encoding=UTF8&me=&qid=1544630778), 4^th^ ed, Springer, New York NY, 2002.

14. Härdle, Wolfgang K \index{Härdle, Wolfgang K}; Léopold Simar; [Applied Multivariable Analysis](http://pascal.upf.edu/am/dades/h-s-mva-book/mvahtml.html),3^rd^ Ed., Springer, New York NY, 2012.

15. George, Janeve [Understanding Programming Paradigms](http://www.janeve.me/software-programming/understanding-programming-paradigms),Bangalore, India, 2013. (Accessed:12/07/2018 1:25PM.)

16. Wikipedia contributors, "Programming paradigm," in Wikipedia, The Free Encyclopedia, https://en.wikipedia.org/w/index.php?title=Programming_paradigm&oldid=871880549 (Accessed:12/07/2018 1:25PM.)

17. Aylett, Andrew; "What is the difference between a module and a script in Python?" https://stackoverflow.com/questions/2996110/what-is-the-difference-between-a-module-and-a-script-in-python, accessed 12/11/2018 2:58PM.

18. Wickham, Hadley \index{Wickham, Hadley} [Advanced R]( https://adv-r.hadley.nz/index.html) Chapman & Hall/CRC The R Series, Abingdon UK, 2014.

19. Black, Kelly; [R Object-Oriented Programming](https://smile.amazon.com/R-Object-oriented-Programming-Kelly-Black-ebook/dp/B00OYTCJQG/ref=sr_1_1?ie=UTF8&qid=1544629643&sr=8-1&keywords=Packt+R+Object-Oriented), Packt Publishing, Birmingham UK, 2014.

20. Chambers, John M \index{Chambers, John M}; [Extending R](https://smile.amazon.com/Extending-Chapman-Hall-John-Chambers-ebook/dp/B01GRHCLG0/ref=mt_kindle?_encoding=UTF8&me=&qid=1544629533), Chapman & Hall/CRC The R Series, Abington UK, 2016.

21. Chang, Winston \index{Chang, Winston} [R6](https://r6.r-lib.org/) with [R Infrastructure Group](https://github.com/r-lib), accessed 12/12/2018 11:27AM.

22. Leisch, Friedrich\index{Leisch, Friedrich}; [Creating R Packages: A Tutoria](https://cran.r-project.org/doc/contrib/Leisch-CreatingPackages.pdf), Compstat 2008-Proceedings
in Computational Statistics.  Physica Verlag, Heidelberg, Germany, 2008. accessed 12/12/2018 3:58PM

23. Schmidt, Drew:\index{Schmidt, Drew} [Package 'Dequer'](https://cran.r-project.org/web/packages/dequer/dequer.pdf), CRAN, 2017.accessed 2018/12/15 9:53AM \index{dequer}

24. Dowle, Matt; \index{Dowle, Matt} [Package 'data.table'](https://cran.r-project.org/web/packages/data.table/data.table.pdf), CRAN, 2018 accessed 2018/12/15 10:00AM \index{data.table}

25. McKinney, Wes et al.; \index{McKinney, William} [Pandas: Powerful Python Data Analysis Toolkit](http://pandas.pydata.org/pandas-docs/stable/pandas.pdf) Pandas Project,2018. accessed: 2018/12/15 10:52AM

26. McKinney, William;\index{McKinney, William} [Python for Data Analysis, 2nd Ed], OReilly, Sebastopol CA, 2017.

27.  Blitzstein, Joe;\index{Blitzsein, Joe et al.} Hwang, Jessica; [Introduction to Probability](https://www.amazon.com/Introduction-Probability-Chapman-Statistical-Science-ebook/dp/B00MMOJ19I), CRC Press, Abington UK 2014. 

28. [Glossary of statistical terms](https://www.statistics.com/glossary) Institute for Statistics Education, Arlington, VA accessed: 2018/12/15 2:51PM

29. The Cambridge English Dictionary,  Cambridge University Press, Cambridge UK, 2018 [Online Dicionary](https://dictionary.cambridge.org/us/) accessed: 2018/12/15 3:335PM.

30. Grinstead, Charles M.; j. Laurie Snell; [Introduction to Probability](https://www.math.dartmouth.edu/~prob/prob/prob.pdf) American Mathematical Society, Providence RI, 2003 accessed: 2018/12/15 3:25PM 

31. Stroock, D.W; Probability theory: an analytic view. Cambridge University Press. Cambridge UK, (1999)

32. Kerns, G Jay; [Introduction to Probability and Statistics with R](https://cran.r-project.org/web/packages/IPSUR/vignettes/IPSUR.pdf), CRAN @ R Foundation for Statistical Computing, Vienna, 2018. accessed:2018/12/15 4:20PM